### ISSUE TITLE
objstr and cyclic object graphs

### ISSUE THREAD

**Issue by adrian-herscu** [gaogaotiantian/objprint#105]
It seems that cyclic object graphs cause an infine recursion.

```python
from objprint import *

config(skip_recursion=True)


class Foo:
    f1: int = 2
    f2: str = "kuku"
    f3: 'Foo'

    def __init__(self):
        self.f3 = Foo()


print(objstr(Foo()))
```

Output:

```
Traceback (most recent call last):
  File "/home/adrian-herscu/projects/pam-2/tests/python/scratch.py", line 15, in <module>
    print(objstr(Foo()))
                 ^^^^^
  File "/home/adrian-herscu/projects/pam-2/tests/python/scratch.py", line 12, in __init__
    self.f3 = Foo()
              ^^^^^
  File "/home/adrian-herscu/projects/pam-2/tests/python/scratch.py", line 12, in __init__
    self.f3 = Foo()
              ^^^^^
  File "/home/adrian-herscu/projects/pam-2/tests/python/scratch.py", line 12, in __init__
    self.f3 = Foo()
              ^^^^^
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by gaogaotiantian** [comment]
There are configurations to skip recursion or set the depth limit.

**Comment by adrian-herscu** [comment]
> There are configurations to skip recursion or set the depth limit.

Updated description with example.

**Comment by gaogaotiantian** [comment]
> Updated description with example.

Your example has nothing to do with `objprint`. That is a real infinite recursion. `print(Foo())` will give you the same thing.

**Comment by adrian-herscu** [comment]
> ```python
> config(skip_recursion=True)
> ```

Thought that `config(skip_recursion=True)` will make it work...
I have to deal with some previous code and it contains such recursive objects, although somewhat more complex.
For logging, I am interested in transforming them into strings.
Then? Any suggestion how to deal with such objects?

**Comment by adrian-herscu** [comment]
that's what happens after too many hours :)
closing
