### ISSUE TITLE
Also print the actual expression whose value is being printed

### ISSUE THREAD

**Issue by riyadparvez** [gaogaotiantian/objprint#49]
The https://github.com/gruns/icecream lib has an useful feature where it also prints the expression. Please see the following example:

```
d = {'key': {1: 'one'}}
ic(d['key'][1])

class klass():
    attr = 'yep'
ic(klass.attr)
```

It prints:
```
ic| d['key'][1]: 'one'
ic| klass.attr: 'yep'
```

As you can see icecream lib also prints the expression **`d['key'][1]`**. Is it possible to add this feature? This is the only feature holding me back from switching to objprint.

**Comment by gaogaotiantian** [comment]
This is doable with some black magic. But I'm a bit hesitated to make the default behavior of `objprint` print metadata, like the full expression of the variable printed.

As an example, you can set `line_number=True` to print the line number and the caller function of the print. Would you consider using argument like this to achieve what you want?

Just as a reminder, you can set the configuration globally by `op.config(line_number=True) `.

The other option is to change the behavior of `objprint`(or `op`, they are the same thing), but keep `objstr` and `add_objprint` as they are probably used in a more delicate case.

Would you mind sharing your thought on this?

**Comment by riyadparvez** [comment]
Thanks for quick response.

I use the `line_number=True` option and it's very helpful. But sometimes printing the expression itself on terminal or log saves me a round-trip to the editor and finding that line of code. I think you can add a config option `print_expression=True` and set the default to `False` similar to `line_number=True`. I thinkit's the best option.

**Comment by gaogaotiantian** [comment]
Hi @riyadparvez . I added the feature requested. You can use ``arg_name=True`` to print the expression. Although it's not released yet. You can use the git master version, or wait for the feature to release. Let me know if you need anything else!
