### ISSUE TITLE
weird escaped characters in jupyter notebook's output

### ISSUE THREAD

**Issue by Asuralf** [gaogaotiantian/objprint#61]
I used pyreadstat module to read a simple SAS file. the code goes like this in jupyter notebook 

```python
import pyreadstat as pyrs
from objprint import op

sas_path = './test_sas/foo.sas7bdat'
df, meta = pyrs.read_sas7bdat(sas_path, metadataonly=True)
# just wanted to check out what meta contains 
op(meta)
```

the brief output of current cell seems normal 
```
Output exceeds the [size limit]. Open the full output data[ in a text editor]
<metadata_container 0x1bcf4bfa3e0
  .column_labels = [
    'projectid',
    'project',
...
    'project': '$'
  },
  .variable_value_labels = {}
>
<pyreadstat._readstat_parser.metadata_container at 0x1bcf4bfa3e0>
```

but after I clicked "in a text editor", the first lines look like this:
```
[36m<metadata_container 0x1bcf4bfa3e0[39m
  [32m.column_labels[39m = [
    'projectid',
    'project',
```
the weird characters actually look like small suqares contains 3 small letters `ESC` in the text editor.

**Comment by gaogaotiantian** [comment]
Those are the ANSI escape characters to colorize the output. If you directly open that in the editor it could output this weird stuff. The simple way to solve this is to simply add ``color=False`` as an argument in ``op()``. You could also set it globally by ``op.config(color=False)``

**Comment by Asuralf** [comment]
thanks, it works
