### ISSUE TITLE
在pycharm中没打印出来

### ISSUE THREAD

**Issue by Conan520** [gaogaotiantian/objprint#63]
![image](https://user-images.githubusercontent.com/66357304/165552232-2eb16366-03d0-45cc-9a93-ee80217c248c.png)
我在我的pycharm中的terminal中运行，好像打印结果不对，不知道是不是我的用法不对还是有bug

**Comment by Conan520** [comment]
是我的问题，我忘了实例化，尴尬

**Comment by gaogaotiantian** [comment]
objprint的color还没fix，估计会在这周完成。

**Comment by gaogaotiantian** [comment]
Fixed in #64
