### ISSUE TITLE
Change the output order of line number and arg name

### ISSUE THREAD

**Issue by riyadparvez** [gaogaotiantian/objprint#67]
For the following example:
```python
from objprint import config, install, objjson, op

config(line_number=True)
config(arg_name=True)

x = 1
op(x)
```

This is the output right now:
```
x:
<module> (/path/to/objprint-test.py:7)
1
```

What I think more intuitive is argument name followed by the value and the file and line number at the top. In this particular case:
```
<module> (/path/to/objprint-test.py:7)
x:
1
```

Any thoughts?

**Comment by gaogaotiantian** [comment]
You are right, it should be fixed.
