### ISSUE TITLE
大佬,objprint可以打印出函数的内容吗？类似于js中console.log()方法。

### ISSUE THREAD

**Issue by xuxiaobo-bobo** [gaogaotiantian/objprint#71]
//JavaScript
function ad(a, b) {

    return a + b;
}

console.log(ad.toString())

//输出
// function ad(a, b) {
//
//     return a + b;
// }

//python
def ad(a,b):
    return a+b
print(ad)
# 输出
# <function ad at 0x000002511B318550>

**Comment by gaogaotiantian** [comment]
Check `inspect.getsource()`
