### ISSUE TITLE
ANSI escape code in Python IDLE Shell 3.9

### ISSUE THREAD

**Issue by VA0AV** [gaogaotiantian/objprint#75]
When I use op() in Python IDLE Shell 3.9, I find IDLE can't display the correct color.
However, PyCharm and cmd can display the correct color.

![image](https://user-images.githubusercontent.com/98648117/180587879-86e949d1-0345-40d5-a4d2-e06fe3cac8f8.png)
![image](https://user-images.githubusercontent.com/98648117/180587903-3c731dbf-801c-4e81-9223-2c9dc58de629.png)
![image](https://user-images.githubusercontent.com/98648117/180587942-6aa08513-728e-4477-a11e-7b9b4ca50bc7.png)
![image](https://user-images.githubusercontent.com/98648117/180587958-e475864b-cc25-4380-8599-257b977be21d.png)

**Comment by gaogaotiantian** [comment]
IDLE does not support ANSI escape codes so color won't work on IDLE. This is not an issue specific to objprint. Considering the very small user base of IDLE, we probably won't write special code just for IDLE. To get a workaround, just do `op.config(color=False)` to turn off color.
