### ISSUE TITLE
no color but random code

### ISSUE THREAD

**Issue by tiebanluyu** [gaogaotiantian/objprint#76]
You have said you fix this bug.But I face it just now.

**Comment by gaogaotiantian** [comment]
Please list your environment including the OS, python version and objprint version. If you are working on windows, are you using cmd or powershell?

**Comment by tiebanluyu** [comment]
windows 7
python 3.8.5
CMD
objprint 0.2.2




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gaogaotiantian/objprint"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 中午12:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gaogaotiantian/objprint] no color but random code (Issue #76)





 
Please list your environment including the OS, python version and objprint version. If you are working on windows, are you using cmd or powershell?

**Comment by gaogaotiantian** [comment]
CMD on Win7 does not support ANSI escape code natively. As Win 7 was discontinued in 2020, there will be nothing done for code that does not work on Win 7. If you have the same issue on Win 10, feel free to reopen this issue.
