### ISSUE TITLE
Duplicate output when op() argument wasn't an object.

### ISSUE THREAD

**Issue by CokeStudios** [gaogaotiantian/objprint#78]
>>> import hashlib
>>> op(hashlib)
<module 'hashlib' from 'C:\\Users\\guojoan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\hashlib.py'>
<module 'hashlib' from 'C:\\Users\\guojoan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\hashlib.py'>

>>> a = []
>>> a.append(a)
>>> op(a)
[[ ... ]]
[[...]]

and so on

**Comment by gaogaotiantian** [comment]
Are you using an REPL? As `op` returns the object, so REPL will print the returned object, which will result in print the object twice(one by `op` and another one by an implicit `print`). This is track in #73 and I probably will figure out a way to detect REPL and change the behavior.

**Comment by CokeStudios** [comment]
Yeah and I'll close this issue.
