### ISSUE TITLE
[BUG] 未抑制读取属性时发生的异常

### ISSUE THREAD

**Issue by Ovizro** [gaogaotiantian/objprint#97]
这是我在使用它打印sqlalchemy的一些对象时发现的问题。
最简单的用例如下：
```py
from objprint import op


class Test:
    __slots__ = ["a"]


op(Test())
```
我获得了一个`AttributeError: a`。这并不是我所预期的，我认为更好的处理方式是ObjPrint抑制异常并忽略此属性。

**Comment by Ovizro** [comment]
简单的加了一个修复，仅针对AttributeError的情况。对于访问property时发生的其他种类的异常，是否应该添加一个选项以选择是否抑制它？

**Comment by gaogaotiantian** [comment]
例子很有趣，想法也不错，实现有问题。这里完全没必要单独去做一个singleton，直接try except AttributeError就行。

**Comment by Ovizro** [comment]
已经做了一下修改，我之前的想法大概是觉得用getattr默认值的性能比try except好一些

**Comment by gaogaotiantian** [comment]
在Python3.11还是哪个版本之后，try except在happy path的时候就已经是零开销了。
